### PR TITLE
Interoperability with other apps with static/dynamic properties

### PR DESCRIPTION
**Pull request by MattMofDoom**
Hi @Hinni,

Hope you're well!  This supersedes and can close #9, as it includes the fixes from that PR.

Since that initial PR in April, I've done quite a bit of work with other authors for packages like Seq.App.OpsGenie and Seq.App.Atlassian.Jira to improve interoperability between applications.  This essentially allows apps like Seq.Input.MSSQL to pass properties as part of their log event, which can be used by an alert app to pass properties to destinations like OpsGenie and Jira.

You can see some background and info on this at https://mattmofdoom.com/passing-priority-responder-and-tags-from-seq-to-opsgenie/, and a recent example of one of my apps leveraging this capability is at https://mattmofdoom.com/event-schedule-v1018-schedule-multiple-log-entries-and-jira-related-enhancements/ following the update to the Seq.Atlassian.Jira app 😀

Seq.Input.MSSQL is quite unique because it's drawing from SQL to populate logs in Seq, so there's an opportunity to be a bit more creative in how we do this. In short - it's possible to contemplate either setting static properties or dynamically passing properties like Tags, Priority, Responders, ProjectKey, InitialEstimate, RemainingEstimate, and DueDate from a SQL query. 

Using the logic we've applied for keypair key=value mapping in the OpsGenie and Jira apps, we can even match possible SQL results to a dictionary of ResultValue=LogValue.  I've already used this to a limited extent with the Jira app evaluating the output from my fork of Seq.Input.MSSQL to map Jira priorities from a view's column.

I have also taken a look at #8 since it's quite possible with these updates, and included the ability to do this. I preserve the existing LogEventLevel setting and it remains an integer; if a log event level can't be mapped from a DB column, this will serve as the default value for the log level 😊

To avoid overburdening the constructor for Executor, I switched the logic to use a static "SqlConfig" class for settings, which is populated via the OnAttached method that runs when the MSSQL Input instance starts.

I've also applied amendments to the csproj to only include the essential DLLs (System.Data.SqlClient.dll and sni.dll) in the Nuget package.

Finally, I updated the test cases to evaluate based on current date so that they no longer fail.

Cheers,

Matt

### CODE REVIEW

**Comment by Hinni** [comment]
Thanks for your contribution. During holidays I have time to review your PR. 😃

**Comment by MattMofDoom** [comment]
@Hinni Added an extension to the original work in #9. For that, I had added code to subtract 1 second from DateTime.Now to allow for cases where the timestamp was not measured in milliseconds.

I now encountered a case where the database rows are only inserted once per minute, and rows can be inserted 'late' (ie. they're inserted after a scan, with a datetime that falls within the last scan).

Hence making this 'delay' configurable with a minimum and default of 1 second, and a maximum of 300 seconds. This works to allow rows to never be missed when configured to an appropriate  delay, and I confirmed that allows the issue that I found to be overcome 😊

**Comment by Hinni** [comment]
Hi @MattMofDoom . Thanks for pushing new changes. I'm back from holidays and ready to check your PR 👍🏼

**Comment by MattMofDoom** [comment]
Welcome mate. I was testing out the new features, they work well after I fixed a logic reversal 😂

**Comment by Hinni** [comment]
Did you test it on Windows and / or in a Docker container?

**Comment by MattMofDoom** [comment]
Yes, we actually use it in production quite extensively, with quite a few databases. Runs on a Windows instance.

**Comment by Hinni** [comment]
@MattMofDoom that's cool.
I test it on my docker playground this evening.

**Comment by MattMofDoom** [comment]
@Hinni Any issues? I usually have my apps hooked up to Appveyor with unit tests configured which tends to help with the cross platform functionality, so curious how you've gone 😊

**Comment by Hinni** [comment]
I struggle in docker with missing dependencies. In the past v1.1.1 included all required files using .

> I've also applied amendments to the csproj to only include the essential DLLs (System.Data.SqlClient.dll and sni.dll) in the Nuget package.

Did you install all dependencies manually on your Windows instance?

**Comment by MattMofDoom** [comment]
No, but it's a good point - Windows vs Docker differences weren't contemplated, and Windows will definitely load absent dependencies available locally, where Docker may not have them to reference. I was just making the package size efficient. I'll reinstate the dependencies to the package specs which should resolve the issue.

**Comment by MattMofDoom** [comment]
@Hinni  I've reinstated the dependencies to the package, apologies for that. I've tested and made sure it's working in both instances that I have access to. Sample logs from something I worked on to pull malware alerts out of a database below 😁

image

**Comment by Hinni** [comment]
Hi @MattMofDoom. Are you able to check from your side with my modification of project RuntimeIdentifier to linux-x64? I was able to run the final package on Seq Docker instance and Windows 10 and I curious about your your environment. Does it work as well?

image

**Comment by Hinni** [comment]
I think we are very near releasing 1.2.0 😄 🎉

**Comment by MattMofDoom** [comment]
No problems, will check and confirm 😁

**Comment by MattMofDoom** [comment]
@Hinni  It's a bit weird, but until I add 

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>`

to the csproj, I wasn't getting all the reference DLLs added to the .nupkg. 

I think you're right that sni.dll isn't needed anymore - I don't see it either. 

Once I was able to package it, I was able to install it to my dev Seq install and configure an instance, started okay. With that successful non-prod test, I was then able to update my prod instance. All working, no errors 😁

**Comment by MattMofDoom** [comment]
Hold on - I've just seen errors in the logs.

**Comment by Hinni** [comment]
I published a preview release of my package version here:
https://www.nuget.org/packages/Seq.Input.MSSql/1.2.0-pre-20210929-001

**Comment by Hinni** [comment]
Take your time to test it - I go to sleep now. Let's release it later this day 😄

**Comment by MattMofDoom** [comment]
@Hinni Yeah, just working out why I got this one. I'll figure it out - sleep well.

`System.Data.SqlClient.SqlException (0x80131904): Unable to load DLL 'System.Net.Security.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Interop.NetSecurityNative.ImportPrincipalName(Status& minorStatus, String inputName, Int32 inputNameByteCount, SafeGssNameHandle& outputName)
   at Microsoft.Win32.SafeHandles.SafeGssNameHandle.CreateTarget(String name)
   at System.Net.Security.SafeDeleteNegoContext..ctor(SafeFreeNegoCredentials credential, String targetName)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, ChannelBinding channelBinding, String targetName, ContextFlagsPal inFlags, Byte[] incomingBlob, Byte[]& resultBuffer, ContextFlagsPal& outFlags)
   at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, Byte[] incomingBlob, ChannelBinding channelBinding, Byte[]& resultBlob, ContextFlagsPal& contextFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Seq.Input.MsSql.Executor.Start()
ClientConnectionId:6b23c76f-48b9-4d09-b293-4315980a4864`

**Comment by MattMofDoom** [comment]
Okay, I've worked it out. It happens on instances where I'm using Trusted Connection enabled, but not when credentials are explicitly provided. We need the best of both worlds so I'll try to figure out what we need there.

**Comment by MattMofDoom** [comment]
@Hinni  Not great news I'm afraid. I spent some time on this and essentially, this is the problem: https://github.com/dotnet/SqlClient/issues/143

Setting the RuntimeIdentifier to linux-x64 affects the overall package. I also tested setting RuntimeIdentifiers with win-x64 and linux-x64, with some strange results. 

I attempted this with both the System.Data.SqlClient and the newer Microsoft.Data.SqlClient. As the Microsoft.Data.SqlClient is the  'current' client, I've left that in place.

Essentially - because the integrated security is reliant on the Windows native library, it gets dropped off when Linux is configured.

I've taken us back to the original runtimeidentifier state of Win-x64. I  do make use of integrated security as well as specifying username and password (depending on the instance requirements) so I don't think we can easily do without the feature. 

It looks like this could run in Docker without integrated security, but it would have to be a separate package to allow the "Windows only" integrated security to work.

**Comment by Hinni** [comment]
Thanks for your effort and update. I was afraid of something like this, since "Integrated Security" is only available on Windows. Okay, let's revert this changes and create a Windows only package. I will work on it this evening.

**Comment by MattMofDoom** [comment]
No problem. Last commit should do the job - have tested and it worked okay against all Windows instances.

**Comment by Hinni** [comment]
I had to fix some small details but I think we are ready now.

Here the final prerelease which should become the release candidate. I hope this package works for you as well. In my test environment it's ok. I have added a note to the README, which points out the Linux problem.
https://www.nuget.org/packages/Seq.Input.MSSql/1.2.0-pre-20210929-002

**Comment by MattMofDoom** [comment]
Thanks @Hinni  - tested in my environment and all working as expected here too 👍 

Once published I think I'll do a blog post or two on how versatile I've found Seq.Input.MSSQL to be, and run through scenarios for turning database queries into Seq logs and then alerts to Opsgenie/Jira 😁

**Comment by Hinni** [comment]
I would like to read your blog posts 👍🏼 😄

**Comment by MattMofDoom** [comment]
@Hinni Here's a start 😁 https://mattmofdoom.com/ingesting-database-queries-as-logs-in-seq-using-seqinputmssql/

**Pull request merged**
